const FETCH_SITUATIONS = "FETCH_SITUATIONS";
const SAVE_SITUATION = "SAVE_SITUATION";
const DELETE_SITUATION = "DELETE_SITUATION";
const ERROR_SITUATION = "ERROR_SITUATION";

const allActions = {
  FETCH_SITUATIONS,
  SAVE_SITUATION,
  DELETE_SITUATION,
  ERROR_SITUATION,
};

export default allActions;
